### ISSUE TITLE
Some informations

### ISSUE THREAD

**Issue by Angelk90** [raymondchooi/react-native-circle-slider#2]
Hi @raymondchooi : 

I tried the project, I congratulate you I wanted to ask you how I could make some changes.

1) Make sure that when you get to 359,360,0,1.
How far you get to 360 freezes, and the only way to get to 0 or 1, you have to go back and not go forward.

2) Make sure to set a min and max.
For example, min, can also be a negative value: -50
For example the max, can be a value different from 360.

I did a test, here is the link: https://snack.expo.io/B1lpHUFMX

**Comment by raymondchooi** [comment]
Hey @Angelk90 ,

I've updated the code so that you the default `max` value is now 359 so it should snap to 0 after this and not reach 360.

You can now set the `min` value too, the default is 0.

If you would like some more control over the value changes you can use the `onValueChange` function like `x => x-50`
